;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Event.Combat.Hitbox.Active",DevComment="")
+GameplayTagList=(Tag="Event.Combat.Hitbox.Inactive",DevComment="")
+GameplayTagList=(Tag="Event.Combat.HitLanded",DevComment="")
+GameplayTagList=(Tag="PlayerAbility.Attack.Katana.Base0.FreeToMove",DevComment="")
+GameplayTagList=(Tag="PlayerAbility.Attack.Katana.Base0.TraceEnd",DevComment="")
+GameplayTagList=(Tag="PlayerAbility.Attack.Katana.Base0.TraceStart",DevComment="")
+GameplayTagList=(Tag="PlayerAbility.Attack.Katana.Base1.TraceEnd",DevComment="")
+GameplayTagList=(Tag="PlayerAbility.Attack.Katana.Base1.TraceStart",DevComment="")
+GameplayTagList=(Tag="PlayerAbility.Attack.Light",DevComment="")
+GameplayTagList=(Tag="PlayerAbility.Attack.Light.TracEnd",DevComment="")
+GameplayTagList=(Tag="PlayerAbility.Attack.Light.TraceStart",DevComment="")
+GameplayTagList=(Tag="PlayerAbility.Hit.LightAttack",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.TryingToMove",DevComment="")
+GameplayTagList=(Tag="Weapon.StraightSword.TestSword",DevComment="")

